### ISSUE TITLE
토큰 기반 인증에 관련해서

### ISSUE THREAD

**Issue by songju7920** [LIFT-dsm/Tunicate#9]
토큰 기반 인증 인가를 사용하고 있는 줄 알았는데, 
토큰 + 세선(서버에서 상태 관리만)으로 구현되어있네요??

이렇게 구현한 것이 잘못됐다가 아니고, 왜 이렇게 구현한 것인지 궁금합니다!
제 생각은 이런 구현 방식이면 토큰, 세션 둘의 장점이 다 없다고 생각합니다..

### 토큰 기반
- 무상태 상실.

### 세션
- 토큰에 정보가 포함되어 있어 서버에서 데이터를 관리하는 의미가 없어짐.

_Originally posted by @ori0o0p in https://github.com/LIFT-dsm/Tunicate/pull/7#pullrequestreview-2288515203_

**Comment by songju7920** [comment]
확실히 Redis를 세션으로 보면 Stateless도 아니고 Session 기반 로그인 장점도 못 챙기겠네요.

하지만 Redis에 토큰을 저장하는 것은 NestJS에서는 필요하다고 생각합니다.
Redis의 인증로직같은 경우, Springboot처럼 철저하지 않기 때문에, 다음과 같은 상황이 발생 할 수 있습니다.

1. user A가 로그인하여 a라는 토큰을 발급받음
2. 토큰 a가 만료되기 전, user A가 다시 로그인을 시도하여 토큰 b를 발급함
3. 하지만, 아직도 토큰 a로 로그인 시도 시 성공적으로 로그인이 가능함.

요약하자면, 기존 토큰 만료기간이 지나기 전 토큰을 새로 발급받는 경우가 생기면 기존 토큰으로도 로그인이 가능해집니다.
생각해보니, 로그아웃 기능은 딱히 필요 없을것 같긴 합니다. 하지만 로그아웃 기능과는 별개로 토큰을 Redis에 저장하는것은 유효성 검사를 위해 필요하다 생각합니다.

좋은 지적 감사합니다 :)
설명에 대한 질문이나 의견 자유롭게 남겨주세요!

**Comment by ori0o0p** [comment]
"토큰 a가 만료되기 전, user A가 다시 로그인을 시도하여 토큰 b를 발급함"

이게 토큰 기반 인증 인가에서 나타날 수 밖에 없는 현상인데, 이게 토큰의 상태를 서버에서 관리해주지 않기 때문이에요.
해당 문제에서는 단일 토큰 정책 또는 완전한 세션을 적용할 수 있는데

단일 토큰 정책을 적용한다고 하면 Redis에서 관리하는 것이 낫겠네요.

이번 PR로 보안의 중요성이 좀 와 닿았던 것 같아요! 👍

**Comment by songju7920** [comment]
생각을 해봤지만, 로그아웃은 딱히 필요 없는 기능같습니다.

위에서 말한 예전 토큰으로 로그인하는 보안적 취약점에 대해 토큰을 Redis에 저장할 필요성은 있지만, 굳이 저장된 토큰을 Redis에서 삭제하는 작업은 필요 없을 것 같습니다. 클라이언트쪽에서 webstorage에 저장된 토큰을 제거하는걸로 로그아웃을 구현하면 충분할 것 같습니다.

결론적으로는, Logout 기능은 제거하는게 맞는것 같습니다.

이번 PR로 제가 당연히 여기던것을 논리적으로 되돌아보고 생각해볼 수 있었던 좋은 기회였던것 같습니다.
이런 좋은 기회 제공해주셔서 감사합니다. 😄

**Comment by songju7920** [comment]
제가 지금 생각을 해봤는데, 로그아웃 기능도 필요할것 같습니다.

로그아웃 한다음에 만료시간이 지나기 전 해당 토큰으로 요청을 보내는 상황도 발생 할 수 있을것 같네요.
로그아웃기능이 필요하긴 할것같아요.

**Comment by songju7920** [comment]
로그아웃 기능을 구현하지 않으면 다음과 같은 상황이 발생할 수 있겠네요

1) A라는 유저가 로그인 후 a라는 토큰을 발급받음
2) B라는 해커가 A의 토큰을 어떠한 방식으로든 탈취함
3) A 유저가 이를 알아채고 빠르게 로그아웃
4) 하지만 a 토큰이 만료되지 않았다면 B 유저가 a토큰으로 통신을 할 수 있음

**Comment by ori0o0p** [comment]
유효한 토큰을 관리하고 있으니까 로그아웃 기능이 필요하겠네요. 👍
로그아웃 기능을 추가하는 쪽으로 가죠
